# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on: [push, pull_request, workflow_dispatch]
permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Show branch name to work on
      run: echo ${{ github.event.inputs.branch }}
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      continue-on-error: true
      run: | 
        mvn -B package --file pom.xml -DskipTests
    - name: Create package
      id: create
      continue-on-error: true
      run: | 
        mkdir staging 
        cp ./edms-aio-platform/target/edms-aio-platform-1.0-SNAPSHOT.jar staging
        cp ./edms-aio-share/target/edms-aio-share-1.0-SNAPSHOT.jar staging
    - name: Upload Package
      id: artifact-upload
      continue-on-error: true
      if: steps.create.outcome == 'success'
      uses: actions/upload-artifact@v4
      with:
        name: Package
        path: staging
    - name: checkout another repo
      uses: actions/checkout@v4
      with:
        repository: UtpalChatterjee-gsa/edms-dist
        token: ${{ secrets.TOKEN }}
        path: edms-dist
    - name: Change directory to edms-dist
      run: cd edms-dist
    - name: Output artifact URL
      if: steps.artifact-upload.outcome == 'success'
      run: echo 'URL is ${{ steps.artifact-upload.outputs.artifact-url }}' > artifact-url-${{ github.event.pull_request.base.ref }}.txt
    - name: Output artifact URL FAILED
      if: steps.artifact-upload.outcome != 'success' || steps.create.outcome != 'success'
      run: echo 'FAILED' > artifact-url-${{ github.event.pull_request.base.ref }}.txt
    - name: Commit artifact-url.txt file
      run:  |
        git config --global user.name "UtpalChatterjee-gsa"
        git config --global user.email "utpal.chatterjee@gsa.gov"
        git add artifact-url.txt
        git commit -m "added / mofified artifact-url-${{ github.event.pull_request.base.ref }}.txt"
        git push
