# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on: [push, pull_request, workflow_dispatch]
permissions:
  contents: write

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: Show branch name to work on
      run: echo ${GITHUB_REF##*/}
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  build_artifact:
    needs: build_and_test
    runs-on: ubuntu-latest
    outputs:
      output_file_name: ${{ steps.output_file.outputs.output_file_name }}
      output_text: ${{ steps.output_artifact.outputs.output_text }}
    if: ${{ github.event_name != 'pull_request' }}
    steps:
    - name: Output File name
      id: output_file
      run: echo "output_file_name=artifact-url-${GITHUB_REF##*/}.txt" >> "$GITHUB_OUTPUT"
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests
    - name: Create package
      id: create
      run: | 
        mkdir staging 
        cp ./edms-aio-platform/target/edms-aio-platform-1.0-SNAPSHOT.jar staging
        cp ./edms-aio-share/target/edms-aio-share-1.0-SNAPSHOT.jar staging
    - name: Upload Package
      id: artifact-upload
      if: steps.create.outcome == 'success'
      uses: actions/upload-artifact@v4
      with:
        name: Package
        path: staging
    - name: Output artifact URL
      id: output_artifact
      if: steps.artifact-upload.outcome == 'success'
      run: echo 'output_text=${{ steps.artifact-upload.outputs.artifact-url }}'  >> "$GITHUB_OUTPUT"
    - name: Output artifact URL FAILED
      if: steps.artifact-upload.outcome != 'success' || steps.create.outcome != 'success'
      run: echo "output_text=FAILED" >> "$GITHUB_OUTPUT"
      
  report:
    needs: build_artifact
    runs-on: ubuntu-latest
    steps:
    - name: checkout UtpalChatterjee-gsa/edms-dist repo
      uses: actions/checkout@v4
      with:
        repository: UtpalChatterjee-gsa/edms-dist
        token: ${{ secrets.TOKEN }}
    - name: Commit ${{needs.build_artifact.outputs.output_file_name}} file
      run:  |
        echo ${{needs.build_artifact.outputs.output_text}} > ${{needs.build_artifact.outputs.output_file_name}}
        git config --global user.name "UtpalChatterjee-gsa"
        git config --global user.email "utpal.chatterjee@gsa.gov"
        git add .
        git commit -m "added / mofified ${{needs.build_artifact.outputs.output_file_name}} file"
        git push
